# config.py

# Configurazione OpenAI
OPENAI_API_KEY = 'OPENAI_API_KEY'
OPENAI_MODEL = "gpt-4o-mini"  # or "gpt-4o"

# Configurazione del prompt
SYSTEM_PROMPT = "SYSTEM_PROMPT"
USER_PROMPT = "USER_PROMPT"

# Configurazione OpenAI
MAX_TOKENS = 4096
TEMPERATURE = 0.7

GITHUB_TOKEN = "GITHUB_TOKEN"
GITHUB_REPO = "USERNAME/REPO_NAME"

# Configurazione email (Optional)
EMAIL_SENDER = "EMAIL_SENDER"
EMAIL_PASSWORD = "EMAIL_PASSWORD"
EMAIL_RECIPIENT = "EMAIL_RECIPIENT"
SMTP_SERVER = "SMTP_SERVER"
SMTP_PORT = 587

# Configurazione Twitter
TWITTER_API_KEY = "TWITTER_API_KEY"
TWITTER_API_SECRET = "TWITTER_API_SECRET"
TWITTER_ACCESS_TOKEN = "TWITTER_ACCESS_TOKEN"
TWITTER_ACCESS_TOKEN_SECRET = "TWITTER_ACCESS_TOKEN_SECRET"

# OAuth 2.0
TWITTER_CLIENT_ID = 'TWITTER_CLIENT_ID'
TWITTER_CLIENT_SECRET = 'TWITTER_CLIENT_SECRET'
TWITTER_BEARER_TOKEN = 'TWITTER_BEARER_TOKEN'

# Lista dei canali YouTube
YOUTUBE_CHANNELS = [
    "https://www.youtube.com/@CHANNEL1/videos",
    "https://www.youtube.com/@CHANNEL2/videos",

    
    # Aggiungi altri canali qui
]

